// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/task4_uniandes_mshernandezg1.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class task4_uniandes_mshernandezg1 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=5;
      Object Q=$fix(GCollections.asSet(0,1));
      $line=6;
      Object \u03A3=$fix(GCollections.asSet('a','b'));
      $line=7;
      Object q=$fix(0);
      $line=8;
      Object F=$fix(GCollections.asSet(1));
      $line=9;
      Object A=$fix($invokeConstructor(GNondeterministicAutomaton.class,new Object[]{Q,\u03A3,q,F,new GMethod(task4_uniandes_mshernandezg1.class,"\u03B4")}));
      $line=10;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,task4_uniandes_mshernandezg1.class,"main",$line);
    }
  }
  public static Object \u03B4(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=14;
      if ($opEqualY(q,0)) {
        $line=15;
        if ($opEqualY(\u03C3,'a')) {
          $line=15;
          $result=GCollections.asSet(0);
          if (true) break $try;
        }
        else {
          $line=16;
          if ($opEqualY(\u03C3,'b')) {
            $line=16;
            $result=GCollections.asSet(0,1);
            if (true) break $try;
          }
        }
      }
      else {
        $line=18;
        if ($opEqualY(q,1)) {
          $line=19;
          if ($opEqualY(\u03C3,'a')) {
            $line=19;
            $result=GCollections.asSet(1);
            if (true) break $try;
          }
        }
      }
      $line=22;
      $result=GCollections.emptySet();
      if (true) break $try;
      $line=23;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,task4_uniandes_mshernandezg1.class,"\u03B4",$line);
    }
    return $result;
  }
}
