// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/task6_uniandes_mshernandezg1.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class task6_uniandes_mshernandezg1 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=5;
      Object \u03A3=$fix(GCollections.asSet('p','q','r','s','(',')','&','|','=','>','<','!','0',' '));
      $line=6;
      Object Q=$fix(GCollections.asSet("start","atom","wait_bin","not1","not2","nand1","nand2","nand3"));
      $line=7;
      Object qI=$fix("start");
      $line=8;
      Object F=$fix(GCollections.asSet("atom"));
      $line=9;
      Object A=$fix($invokeConstructor(GNondeterministicAutomaton.class,new Object[]{Q,\u03A3,qI,F,new GMethod(task6_uniandes_mshernandezg1.class,"\u03B4")}));
      $line=10;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,task6_uniandes_mshernandezg1.class,"main",$line);
    }
  }
  public static Object \u03B4(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=13;
      if ($opEqualY(\u03C3,' ')) {
        $line=13;
        $result=GCollections.asSet(q);
        if (true) break $try;
      }
      $line=15;
      if ($opEqualY(q,"start")) {
        $line=16;
        if ($opMembrY(\u03C3,GCollections.asSet('p','q','r','s'))) {
          $line=16;
          $result=GCollections.asSet("atom");
          if (true) break $try;
        }
        $line=17;
        if ($opEqualY(\u03C3,'(')) {
          $line=17;
          $result=GCollections.asSet("start");
          if (true) break $try;
        }
        $line=18;
        if ($opEqualY(\u03C3,'|')) {
          $line=18;
          $result=GCollections.asSet("not1");
          if (true) break $try;
        }
      }
      else {
        $line=19;
        if ($opEqualY(q,"atom")) {
          $line=20;
          if ($opEqualY(\u03C3,')')) {
            $line=20;
            $result=GCollections.asSet("atom");
            if (true) break $try;
          }
          $line=21;
          if ($opEqualY(\u03C3,'&')) {
            $line=21;
            $result=GCollections.asSet("wait_bin");
            if (true) break $try;
          }
          $line=22;
          if ($opEqualY(\u03C3,'|')) {
            $line=22;
            $result=GCollections.asSet("wait_bin");
            if (true) break $try;
          }
          $line=23;
          if ($opEqualY(\u03C3,'=')) {
            $line=23;
            $result=GCollections.asSet("nand1");
            if (true) break $try;
          }
          $line=24;
          if ($opEqualY(\u03C3,'<')) {
            $line=24;
            $result=GCollections.asSet("wait_bin");
            if (true) break $try;
          }
        }
        else {
          $line=25;
          if ($opEqualY(q,"wait_bin")) {
            $line=26;
            if ($opMembrY(\u03C3,GCollections.asSet('&','|','=','>','<'))) {
              $line=26;
              $result=GCollections.asSet("start");
              if (true) break $try;
            }
          }
          else {
            $line=27;
            if ($opEqualY(q,"nand1")) {
              $line=28;
              if ($opEqualY(\u03C3,'>')) {
                $line=28;
                $result=GCollections.asSet("start");
                if (true) break $try;
              }
              $line=29;
              if ($opEqualY(\u03C3,'|')) {
                $line=29;
                $result=GCollections.asSet("nand2");
                if (true) break $try;
              }
            }
            else {
              $line=30;
              if ($opEqualY(q,"nand2")) {
                $line=31;
                if ($opEqualY(\u03C3,')')) {
                  $line=31;
                  $result=GCollections.asSet("nand3");
                  if (true) break $try;
                }
              }
              else {
                $line=32;
                if ($opEqualY(q,"nand3")) {
                  $line=33;
                  if ($opEqualY(\u03C3,'0')) {
                    $line=33;
                    $result=GCollections.asSet("start");
                    if (true) break $try;
                  }
                }
                else {
                  $line=34;
                  if ($opEqualY(q,"not1")) {
                    $line=35;
                    if ($opEqualY(\u03C3,'>')) {
                      $line=35;
                      $result=GCollections.asSet("not2");
                      if (true) break $try;
                    }
                    $line=36;
                    if ($opEqualY(\u03C3,'|')) {
                      $line=36;
                      $result=GCollections.asSet("start");
                      if (true) break $try;
                    }
                  }
                  else {
                    $line=37;
                    if ($opEqualY(q,"not2")) {
                      $line=38;
                      if ($opEqualY(\u03C3,'0')) {
                        $line=38;
                        $result=GCollections.asSet("start");
                        if (true) break $try;
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=41;
      $result=GCollections.emptySet();
      if (true) break $try;
      $line=42;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,task6_uniandes_mshernandezg1.class,"\u03B4",$line);
    }
    return $result;
  }
}
