// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/task3_uniandes_mshernandezg1.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class task3_uniandes_mshernandezg1 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=6;
      Object Q=$fix(GCollections.asSet("A","C","D","E"));
      $line=7;
      Object \u03A3=$fix($opIntvlY('a','b'));
      $line=8;
      Object q_0=$fix("E");
      $line=9;
      Object F=$fix(GCollections.asSet("C"));
      $line=10;
      Object \u0394=$fix(new Object[]{new Object[]{"A",'\u03BB',"C"},new Object[]{"A",'a',"D"},new Object[]{"D",'\u03BB',"C"},new Object[]{"C",'\u03BB',"E"},new Object[]{"E",'a',"E"},new Object[]{"E",'b',"E"},new Object[]{"E",'b',"A"}});
      $line=14;
      Object A=$fix($invokeConstructor(GNondeterministicAutomaton.class,new Object[]{Q,\u03A3,q_0,F,\u0394}));
      $line=15;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,task3_uniandes_mshernandezg1.class,"main",$line);
    }
  }
}
