// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/task5.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class task5 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=5;
      Object Q=$fix(GCollections.asSet("init","A","B","C","W","Z"));
      $line=6;
      Object \u03A3=$fix(GCollections.asSet('a','b'));
      $line=7;
      Object qI=$fix("init");
      $line=8;
      Object F=$fix(GCollections.asSet("C","Z"));
      $line=10;
      Object A=$fix($invokeConstructor(GNondeterministicAutomaton.class,new Object[]{Q,\u03A3,qI,F,new GMethod(task5.class,"\u03B4")}));
      $line=11;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,task5.class,"main",$line);
    }
  }
  public static Object \u03B4(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=15;
      if (($opEqualY(q,"init")&&$opEqualY(\u03C3,'\u03BB'))) {
        $line=15;
        $result=GCollections.asSet("A","W");
        if (true) break $try;
      }
      $line=16;
      if ($opEqualY(q,"A")) {
        $line=17;
        if ($opEqualY(\u03C3,'a')) {
          $line=17;
          $result=GCollections.asSet("A","B");
          if (true) break $try;
        }
        else {
          $line=18;
          if ($opEqualY(\u03C3,'b')) {
            $line=18;
            $result=GCollections.asSet("A");
            if (true) break $try;
          }
        }
      }
      else {
        $line=20;
        if ($opEqualY(q,"B")) {
          $line=21;
          if ($opEqualY(\u03C3,'a')) {
            $line=21;
            $result=GCollections.asSet("C");
            if (true) break $try;
          }
          else {
            $line=22;
            if ($opEqualY(\u03C3,'b')) {
              $line=22;
              $result=GCollections.asSet("A");
              if (true) break $try;
            }
          }
        }
        else {
          $line=24;
          if (($opEqualY(q,"C")&&$opEqualY(\u03C3,'\u03BB'))) {
            $line=24;
            $result=GCollections.asSet("A");
            if (true) break $try;
          }
          else {
            $line=25;
            if ($opEqualY(q,"W")) {
              $line=26;
              if ($opEqualY(\u03C3,'a')) {
                $line=26;
                $result=GCollections.asSet("W");
                if (true) break $try;
              }
              else {
                $line=27;
                if ($opEqualY(\u03C3,'b')) {
                  $line=27;
                  $result=GCollections.asSet("W","Z");
                  if (true) break $try;
                }
              }
            }
            else {
              $line=29;
              if ($opEqualY(q,"Z")) {
                $line=30;
                if ((($opEqualY(\u03C3,'a')||$opEqualY(\u03C3,'b'))||$opEqualY(\u03C3,'\u03BB'))) {
                  $line=30;
                  $result=GCollections.asSet("Z");
                  if (true) break $try;
                }
              }
            }
          }
        }
      }
      $line=33;
      $result=GCollections.emptySet();
      if (true) break $try;
      $line=34;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,task5.class,"\u03B4",$line);
    }
    return $result;
  }
}
