// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/task2.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class task2 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=5;
      Object Q=$fix(GCollections.asSet(0,1,2,3,4,5));
      $line=6;
      Object \u03A3=$fix(GCollections.asSet('0','1','2'));
      $line=7;
      Object q=$fix(0);
      $line=8;
      Object F=$fix(GCollections.asSet(3));
      $line=9;
      Object A=$fix($invokeConstructor(GDeterministicAutomaton.class,new Object[]{Q,\u03A3,q,F,new GMethod(task2.class,"\u03B4")}));
      $line=10;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,task2.class,"main",$line);
    }
  }
  public static Object \u03B4(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=14;
      if ($opEqualY(\u03C3,'1')) {
        $line=15;
        if ($opEqualY(q,0)) {
          $line=15;
          $result=3;
          if (true) break $try;
        }
        else {
          $line=15;
          if ($opEqualY(q,1)) {
            $line=15;
            $result=4;
            if (true) break $try;
          }
          else {
            $line=15;
            if ($opEqualY(q,2)) {
              $line=15;
              $result=5;
              if (true) break $try;
            }
            else {
              $line=16;
              if ($opEqualY(q,3)) {
                $line=16;
                $result=0;
                if (true) break $try;
              }
              else {
                $line=16;
                if ($opEqualY(q,4)) {
                  $line=16;
                  $result=1;
                  if (true) break $try;
                }
                else {
                  $line=16;
                  if ($opEqualY(q,5)) {
                    $line=16;
                    $result=2;
                    if (true) break $try;
                  }
                  else {
                    $line=17;
                    $result=q;
                    if (true) break $try;
                  }
                }
              }
            }
          }
        }
      }
      else {
        $line=18;
        if ($opEqualY(\u03C3,'2')) {
          $line=19;
          if ($opEqualY(q,0)) {
            $line=19;
            $result=1;
            if (true) break $try;
          }
          else {
            $line=19;
            if ($opEqualY(q,1)) {
              $line=19;
              $result=2;
              if (true) break $try;
            }
            else {
              $line=19;
              if ($opEqualY(q,2)) {
                $line=19;
                $result=0;
                if (true) break $try;
              }
              else {
                $line=20;
                if ($opEqualY(q,3)) {
                  $line=20;
                  $result=4;
                  if (true) break $try;
                }
                else {
                  $line=20;
                  if ($opEqualY(q,4)) {
                    $line=20;
                    $result=5;
                    if (true) break $try;
                  }
                  else {
                    $line=20;
                    if ($opEqualY(q,5)) {
                      $line=20;
                      $result=3;
                      if (true) break $try;
                    }
                    else {
                      $line=21;
                      $result=q;
                      if (true) break $try;
                    }
                  }
                }
              }
            }
          }
        }
        else {
          $line=22;
          $result=q;
          if (true) break $try;
        }
      }
      $line=23;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,task2.class,"\u03B4",$line);
    }
    return $result;
  }
}
